/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visualize;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JTextField;

/**
 *
 * @author Sule
 */
public class StartDialog extends javax.swing.JDialog {

    private JFileChooser fileChooser = new JFileChooser();
    private int indexOfAnnotatedPeaks = 0;
    private boolean isSpectraLoaded = false,
            isScoreFileLoaded = false;
    private String specFolder = "";

    /**
     * Creates new form StartJDialog
     */
    public StartDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        this.setSize(750, 300);
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Dimension screenSize = toolkit.getScreenSize();
        int x = (screenSize.width - this.getWidth()) / 2,
                y = (screenSize.height - this.getHeight()) / 2;
        this.setLocation(x, y);
        setVisible(true);
    }

    public JTextField getPathSpectrumFolderjTextField() {
        return pathSpecsFolderjTextField;
    }

    public JTextField getPathToScoreFilejTextField() {
        return pathToResultFilejTextField;
    }

    public String getSpecFolder() {
        return specFolder;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        specsFolderjPanel = new javax.swing.JPanel();
        pathSpecsFolderjLabel = new javax.swing.JLabel();
        pathSpecsFolderjTextField = new javax.swing.JTextField();
        browseSpecsjButton = new javax.swing.JButton();
        clearSpecsjButton = new javax.swing.JButton();
        resultFilejPanel = new javax.swing.JPanel();
        pathToResultFilejTextField = new javax.swing.JTextField();
        pathToResultFilejLabel = new javax.swing.JLabel();
        browseResultFilejButton = new javax.swing.JButton();
        clearResultFilejButton = new javax.swing.JButton();
        indexjLabel = new javax.swing.JLabel();
        indexjTextField = new javax.swing.JTextField();
        createjButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Xilmass results viewer graphical user interface");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        specsFolderjPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Spectrum folder"));
        specsFolderjPanel.setOpaque(false);

        pathSpecsFolderjLabel.setText("A path of a spectrum folder");
        pathSpecsFolderjLabel.setToolTipText("Provide a folder for spectra that were searched");

        browseSpecsjButton.setText("Browse");
        browseSpecsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseSpecsjButtonActionPerformed(evt);
            }
        });

        clearSpecsjButton.setText("Clear");
        clearSpecsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearSpecsjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout specsFolderjPanelLayout = new javax.swing.GroupLayout(specsFolderjPanel);
        specsFolderjPanel.setLayout(specsFolderjPanelLayout);
        specsFolderjPanelLayout.setHorizontalGroup(
            specsFolderjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(specsFolderjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pathSpecsFolderjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pathSpecsFolderjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(browseSpecsjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearSpecsjButton)
                .addContainerGap())
        );
        specsFolderjPanelLayout.setVerticalGroup(
            specsFolderjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, specsFolderjPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(specsFolderjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pathSpecsFolderjLabel)
                    .addComponent(pathSpecsFolderjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseSpecsjButton)
                    .addComponent(clearSpecsjButton))
                .addContainerGap())
        );

        resultFilejPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Result file"));
        resultFilejPanel.setOpaque(false);

        pathToResultFilejLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pathToResultFilejLabel.setText("A path of a result file");
        pathToResultFilejLabel.setToolTipText("Provide one Xilmass result file");
        pathToResultFilejLabel.setFocusable(false);
        pathToResultFilejLabel.setMaximumSize(new java.awt.Dimension(172, 15));
        pathToResultFilejLabel.setMinimumSize(new java.awt.Dimension(172, 15));
        pathToResultFilejLabel.setPreferredSize(new java.awt.Dimension(172, 15));
        pathToResultFilejLabel.setRequestFocusEnabled(false);

        browseResultFilejButton.setText("Browse");
        browseResultFilejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseResultFilejButtonActionPerformed(evt);
            }
        });

        clearResultFilejButton.setText("Clear");

        indexjLabel.setText("Index of annotated peaks");
        indexjLabel.setToolTipText("Counting starts from 1, this value equals to 27 on the original output for each mgf files at Xilmass 0.3, and Xilmass 0.4");

        indexjTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        indexjTextField.setText("27");

        javax.swing.GroupLayout resultFilejPanelLayout = new javax.swing.GroupLayout(resultFilejPanel);
        resultFilejPanel.setLayout(resultFilejPanelLayout);
        resultFilejPanelLayout.setHorizontalGroup(
            resultFilejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultFilejPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(resultFilejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pathToResultFilejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(indexjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(resultFilejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(resultFilejPanelLayout.createSequentialGroup()
                        .addComponent(pathToResultFilejTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(browseResultFilejButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearResultFilejButton))
                    .addGroup(resultFilejPanelLayout.createSequentialGroup()
                        .addComponent(indexjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        resultFilejPanelLayout.setVerticalGroup(
            resultFilejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultFilejPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(resultFilejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pathToResultFilejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pathToResultFilejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseResultFilejButton)
                    .addComponent(clearResultFilejButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(resultFilejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(indexjLabel)
                    .addComponent(indexjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        createjButton.setText("CREATE");
        createjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(createjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(specsFolderjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(resultFilejPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(specsFolderjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resultFilejPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createjButton)
                .addContainerGap())
        );

        resultFilejPanel.getAccessibleContext().setAccessibleName("result_file");

        getAccessibleContext().setAccessibleName("Project creation");
        getAccessibleContext().setAccessibleDescription("Open required files");
        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void browseSpecsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseSpecsjButtonActionPerformed
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fileChooser.setMultiSelectionEnabled(true);
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File folder = fileChooser.getSelectedFile();
            specFolder = folder.getAbsolutePath();
            pathSpecsFolderjTextField.setText(folder.getAbsolutePath());
            isSpectraLoaded = true;
        } else {
            System.exit(0);
            System.out.println("File access is cancelled by user.");
        }
    }//GEN-LAST:event_browseSpecsjButtonActionPerformed

    public JTextField getIndexjTextField() {
        return indexjTextField;
    }

    public void setIndexjTextField(JTextField indexjTextField) {
        this.indexjTextField = indexjTextField;
    }

    public int getIndexOfAnnotatedPeaks() {
        indexOfAnnotatedPeaks = Integer.parseInt(indexjTextField.getText().toString());
        return indexOfAnnotatedPeaks;
    }

    private void clearSpecsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearSpecsjButtonActionPerformed
        pathSpecsFolderjTextField.setText("");
    }//GEN-LAST:event_clearSpecsjButtonActionPerformed

    private void browseResultFilejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseResultFilejButtonActionPerformed
        // prepare the data and load a file
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            pathToResultFilejTextField.setText(file.getPath());
            isScoreFileLoaded = true;
        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_browseResultFilejButtonActionPerformed

    private void createjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createjButtonActionPerformed
        if (isScoreFileLoaded && isSpectraLoaded) {
            this.setVisible(false);
        }
    }//GEN-LAST:event_createjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseResultFilejButton;
    private javax.swing.JButton browseSpecsjButton;
    private javax.swing.JButton clearResultFilejButton;
    private javax.swing.JButton clearSpecsjButton;
    private javax.swing.JButton createjButton;
    private javax.swing.JLabel indexjLabel;
    private javax.swing.JTextField indexjTextField;
    private javax.swing.JLabel pathSpecsFolderjLabel;
    private javax.swing.JTextField pathSpecsFolderjTextField;
    private javax.swing.JLabel pathToResultFilejLabel;
    private javax.swing.JTextField pathToResultFilejTextField;
    private javax.swing.JPanel resultFilejPanel;
    private javax.swing.JPanel specsFolderjPanel;
    // End of variables declaration//GEN-END:variables
}
