package gui;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JTextField;

/**
 * The GUI main frame.
 *
 * @author Niels Hulstaert
 */
public class MainFrame extends javax.swing.JFrame {

    private final JFileChooser spectraDirectoryChooser = new JFileChooser();
    private final JFileChooser comparisonSpectraDirectoryChooser = new JFileChooser();
    private final JFileChooser outputDirectoryChooser = new JFileChooser();

    /**
     * Constructor.
     */
    public MainFrame() {
        initComponents();
    }

    public JFileChooser getSpectraDirectoryChooser() {
        return spectraDirectoryChooser;
    }

    public JFileChooser getComparisonSpectraDirectoryChooser() {
        return comparisonSpectraDirectoryChooser;
    }

    public JFileChooser getOutputDirectoryChooser() {
        return outputDirectoryChooser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jMenu1 = new javax.swing.JMenu();
        mainPanel = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        mainTabbedPane = new javax.swing.JTabbedPane();
        inputOutputPanel = new javax.swing.JPanel();
        outputDirectoryPathTextField = new javax.swing.JTextField();
        fastaDbPathLabel = new javax.swing.JLabel();
        contaminantsFastaDbPathTextField = new javax.swing.JTextField();
        contaminantsFastaDbBrowseButton = new javax.swing.JButton();
        contaminantsFastaDbFilePathLabel = new javax.swing.JLabel();
        fastaDbPathTextField = new javax.swing.JTextField();
        fastaDbBrowseButton = new javax.swing.JButton();
        searchDbPathLabel = new javax.swing.JLabel();
        searchDbBrowseButton = new javax.swing.JButton();
        outputDirectoryPathLabel = new javax.swing.JLabel();
        searchDbPathTextField1 = new javax.swing.JTextField();
        outputDirectoryBrowseButton = new javax.swing.JButton();
        validatedTargetHitsPathLabel = new javax.swing.JLabel();
        validatedTargetHitsPathTextField = new javax.swing.JTextField();
        validatedTargetHitsBrowseButton = new javax.swing.JButton();
        xpsmsPathLabel = new javax.swing.JLabel();
        xpsmsPathTextField = new javax.swing.JTextField();
        xpsmsBrowseButton = new javax.swing.JButton();
        crossLinkingPanel = new javax.swing.JPanel();
        crossLinkerLabel = new javax.swing.JLabel();
        crossLinkerComboBox = new javax.swing.JComboBox<>();
        crossLinkerLabel1 = new javax.swing.JLabel();
        labelingComboBox = new javax.swing.JComboBox<>();
        sideReactionsLabel = new javax.swing.JLabel();
        serineCheckBox = new javax.swing.JCheckBox();
        threonineCheckBox = new javax.swing.JCheckBox();
        tyrosineCheckBox = new javax.swing.JCheckBox();
        crossLinkingTypeLabel = new javax.swing.JLabel();
        crosslinkingTypeComboBox = new javax.swing.JComboBox<>();
        monolinkingLabel = new javax.swing.JLabel();
        monoLinkingCheckBox = new javax.swing.JCheckBox();
        peptideLengthsLabel = new javax.swing.JLabel();
        minimumPeptideLengthLabel = new javax.swing.JLabel();
        maximumPeptideLengthLabel = new javax.swing.JLabel();
        minimumPeptideLengthTextField = new javax.swing.JTextField();
        maximumPeptideLengthTextField = new javax.swing.JTextField();
        intralinkingLabel = new javax.swing.JLabel();
        intraLinkingCheckBox = new javax.swing.JCheckBox();
        inSilicoDigestionPanel = new javax.swing.JPanel();
        enzymeComboBox = new javax.swing.JComboBox<>();
        misCleavagesLabel = new javax.swing.JLabel();
        misCleavagesTextField = new javax.swing.JTextField();
        minimumPeptideMassLabel = new javax.swing.JLabel();
        minimumPeptideMassTextField = new javax.swing.JTextField();
        maximumPeptideMassLabel = new javax.swing.JLabel();
        maximumPeptideMassTextField = new javax.swing.JTextField();
        enzymeLabel = new javax.swing.JLabel();
        modificationsPanel = new javax.swing.JPanel();
        fixedModificationsPanel = new javax.swing.JPanel();
        fixedModificationsDualList = new gui.DualList();
        fixedModificationsLabel = new javax.swing.JLabel();
        variableModificationsPanel = new javax.swing.JPanel();
        variableModificationsList = new gui.DualList();
        variableModificationsLabel = new javax.swing.JLabel();
        otherModSettingsPanel = new javax.swing.JPanel();
        maxModPeptideLabel = new javax.swing.JLabel();
        maxModPeptideTextField = new javax.swing.JTextField();
        scoringPanel = new javax.swing.JPanel();
        neutralLossesLabel = new javax.swing.JLabel();
        neutralLossesComboBox = new javax.swing.JComboBox<>();
        fragmentationLabel = new javax.swing.JLabel();
        fragmentationModeComboBox = new javax.swing.JComboBox<>();
        peptideMassToleranceWindowsPanel = new javax.swing.JPanel();
        firstPeptideMassToleranceWindowValueLabel = new javax.swing.JLabel();
        firstPeptideMassToleranceWindowTextField = new javax.swing.JTextField();
        firstPeptideMassToleranceWindowUnitLabel = new javax.swing.JLabel();
        firstPeptideMassToleranceWindowUnitComboBox = new javax.swing.JComboBox<>();
        secondPeptideMassToleranceWindowValueLabel = new javax.swing.JLabel();
        secondPeptideMassToleranceWindowTextField = new javax.swing.JTextField();
        secondPeptideMassToleranceWindowUnitLabel = new javax.swing.JLabel();
        secondPeptideMassToleranceWindowUnitComboBox = new javax.swing.JComboBox<>();
        thirdPeptideMassToleranceWindowValueLabel = new javax.swing.JLabel();
        thirdPeptideMassToleranceWindowTextField = new javax.swing.JTextField();
        thirdPeptideMassToleranceWindowUnitLabel = new javax.swing.JLabel();
        thirdPeptideMassToleranceWindowUnitComboBox = new javax.swing.JComboBox<>();
        fourthPeptideMassToleranceWindowValueLabel = new javax.swing.JLabel();
        fourthPeptideMassToleranceWindowTextField = new javax.swing.JTextField();
        fourthPeptideMassToleranceWindowUnitLabel = new javax.swing.JLabel();
        fourthPeptideMassToleranceWindowUnitComboBox = new javax.swing.JComboBox<>();
        jCheckBox1 = new javax.swing.JCheckBox();
        peptideToleranceSpinner = new javax.swing.JSpinner();
        peptideToleranceLabel = new javax.swing.JLabel();
        commonPeptideMassToleranceWindowLabel = new javax.swing.JLabel();
        commonPeptideMassToleranceWindowTextField = new javax.swing.JTextField();
        commonPeptideMassToleranceWindowUnitLabel = new javax.swing.JLabel();
        commonPeptideMassToleranceWindowUnitComboBox = new javax.swing.JComboBox<>();
        minNumberOfPeaksLabel = new javax.swing.JLabel();
        minNumberOfPeaksTextField = new javax.swing.JTextField();
        peakMatchingLabel = new javax.swing.JLabel();
        peakMatchingComboBox = new javax.swing.JComboBox<>();
        spectrumPreprocessingPanel = new javax.swing.JPanel();
        spectrumMassWindowValueLabel = new javax.swing.JLabel();
        spectrumMassWindowValueTextField = new javax.swing.JTextField();
        minimumNumberOfPeaksLabel = new javax.swing.JLabel();
        minimumNumberOfPeaksTextField = new javax.swing.JTextField();
        maximumNumberOfPeaksLabel = new javax.swing.JLabel();
        maximumNumberOfPeaksTextField = new javax.swing.JTextField();
        lowerPrecursorMassBoundLabel = new javax.swing.JLabel();
        lowerPrecursorMassBoundTextField = new javax.swing.JTextField();
        deisotopeLabel = new javax.swing.JLabel();
        deisotopePrecisionTextField = new javax.swing.JTextField();
        deconvulatePrecisionLabel = new javax.swing.JLabel();
        deconvulatePrecisionTextField = new javax.swing.JTextField();
        multiThreadingAndValidationPanel = new javax.swing.JPanel();
        numberOfThreadsLabel = new javax.swing.JLabel();
        numberOfThreadsTextField = new javax.swing.JTextField();
        writePercolatorInputFilesLabel = new javax.swing.JLabel();
        writePercolatorInputFilesComboBox = new javax.swing.JComboBox<>();
        fdrCalculationLabel = new javax.swing.JLabel();
        fdrCalcalationComboBox = new javax.swing.JComboBox<>();
        globalFdrValueLabel = new javax.swing.JLabel();
        globalFdrValueTextField = new javax.swing.JTextField();
        interProteinFdrValueLabel = new javax.swing.JLabel();
        interProteinFdrValueTextField = new javax.swing.JTextField();
        intraProteinFdrValueLabel = new javax.swing.JLabel();
        intraProteinFdrValueTextField = new javax.swing.JTextField();
        bottomPanel = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();
        runButton = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setPreferredSize(new java.awt.Dimension(0, 0));

        topPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        topPanel.setOpaque(false);
        topPanel.setPreferredSize(new java.awt.Dimension(10, 10));

        inputOutputPanel.setOpaque(false);

        fastaDbPathLabel.setText("Select the FASTA database (target-decoy, decoys must plit by \"_\")*:");
        fastaDbPathLabel.setToolTipText("give a folder that contains spectra");

        contaminantsFastaDbBrowseButton.setText("browse...");

        contaminantsFastaDbFilePathLabel.setText("Select an optional contaminants FASTA database:");
        contaminantsFastaDbFilePathLabel.setToolTipText("give a folder that contains spectra");

        fastaDbBrowseButton.setText("browse...");

        searchDbPathLabel.setText("Select the cross-linked and mono-linked peptides search database*:");
        searchDbPathLabel.setToolTipText("give a folder that contains spectra");

        searchDbBrowseButton.setText("browse...");

        outputDirectoryPathLabel.setText("Select the output files directory*:");
        outputDirectoryPathLabel.setToolTipText("give a folder that contains spectra");

        outputDirectoryBrowseButton.setText("browse...");

        validatedTargetHitsPathLabel.setText("Select the validated list of target hits*:");
        validatedTargetHitsPathLabel.setToolTipText("give a folder that contains spectra");

        validatedTargetHitsBrowseButton.setText("browse...");

        xpsmsPathLabel.setText("Select the merged XPSMs*:");
        xpsmsPathLabel.setToolTipText("give a folder that contains spectra");

        xpsmsBrowseButton.setText("browse...");

        javax.swing.GroupLayout inputOutputPanelLayout = new javax.swing.GroupLayout(inputOutputPanel);
        inputOutputPanel.setLayout(inputOutputPanelLayout);
        inputOutputPanelLayout.setHorizontalGroup(
            inputOutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputOutputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputOutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputOutputPanelLayout.createSequentialGroup()
                        .addComponent(fastaDbPathTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fastaDbBrowseButton))
                    .addGroup(inputOutputPanelLayout.createSequentialGroup()
                        .addComponent(contaminantsFastaDbPathTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contaminantsFastaDbBrowseButton))
                    .addGroup(inputOutputPanelLayout.createSequentialGroup()
                        .addComponent(searchDbPathTextField1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchDbBrowseButton))
                    .addGroup(inputOutputPanelLayout.createSequentialGroup()
                        .addComponent(outputDirectoryPathTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(outputDirectoryBrowseButton))
                    .addGroup(inputOutputPanelLayout.createSequentialGroup()
                        .addComponent(validatedTargetHitsPathTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(validatedTargetHitsBrowseButton))
                    .addGroup(inputOutputPanelLayout.createSequentialGroup()
                        .addGroup(inputOutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fastaDbPathLabel)
                            .addComponent(contaminantsFastaDbFilePathLabel)
                            .addComponent(searchDbPathLabel)
                            .addComponent(outputDirectoryPathLabel)
                            .addComponent(validatedTargetHitsPathLabel)
                            .addComponent(xpsmsPathLabel))
                        .addGap(0, 513, Short.MAX_VALUE))
                    .addGroup(inputOutputPanelLayout.createSequentialGroup()
                        .addComponent(xpsmsPathTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xpsmsBrowseButton)))
                .addContainerGap())
        );
        inputOutputPanelLayout.setVerticalGroup(
            inputOutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputOutputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fastaDbPathLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inputOutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fastaDbPathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fastaDbBrowseButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contaminantsFastaDbFilePathLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inputOutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contaminantsFastaDbPathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contaminantsFastaDbBrowseButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchDbPathLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inputOutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchDbBrowseButton)
                    .addComponent(searchDbPathTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(outputDirectoryPathLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inputOutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outputDirectoryPathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outputDirectoryBrowseButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(validatedTargetHitsPathLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inputOutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(validatedTargetHitsPathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(validatedTargetHitsBrowseButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(xpsmsPathLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inputOutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xpsmsPathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xpsmsBrowseButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("Input/Output", inputOutputPanel);

        crossLinkingPanel.setOpaque(false);

        crossLinkerLabel.setText("Select the cross-linker*:");

        crossLinkerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DSS", "BS3", "EDC", "GA", " ", " " }));

        crossLinkerLabel1.setText("Select the labeling*:");

        labelingComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "light", "heavy", "both", " ", " " }));

        sideReactionsLabel.setText("Consider side reactions (only for N-hydroxysuccinimide cross-linkers, such as DSS and BS3) for:");

        serineCheckBox.setText("serine");

        threonineCheckBox.setText("threonine");

        tyrosineCheckBox.setText("tyrosine");

        crossLinkingTypeLabel.setText("Select the labeling*:");

        crosslinkingTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "intra (within same protein)", "inter (between different proteins)", "both", " ", " " }));

        monolinkingLabel.setText("Mono-linking*:");

        monoLinkingCheckBox.setText("search for monolinked peptides");

        peptideLengthsLabel.setText("Cross-linked peptide lengths:");

        minimumPeptideLengthLabel.setText("Minimum peptide length*:");

        maximumPeptideLengthLabel.setText("Maximum peptide length*:");

        minimumPeptideLengthTextField.setMinimumSize(new java.awt.Dimension(62, 27));
        minimumPeptideLengthTextField.setPreferredSize(new java.awt.Dimension(62, 27));

        maximumPeptideLengthTextField.setMinimumSize(new java.awt.Dimension(62, 27));
        maximumPeptideLengthTextField.setPreferredSize(new java.awt.Dimension(62, 27));

        intralinkingLabel.setText("Intra-linking*:");

        intraLinkingCheckBox.setText("allow linkage of a peptide to itself");

        javax.swing.GroupLayout crossLinkingPanelLayout = new javax.swing.GroupLayout(crossLinkingPanel);
        crossLinkingPanel.setLayout(crossLinkingPanelLayout);
        crossLinkingPanelLayout.setHorizontalGroup(
            crossLinkingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crossLinkingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(crossLinkingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(crossLinkerLabel)
                    .addComponent(crossLinkerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crossLinkerLabel1)
                    .addComponent(labelingComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crossLinkingTypeLabel)
                    .addComponent(crosslinkingTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(crossLinkingPanelLayout.createSequentialGroup()
                        .addComponent(monolinkingLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(monoLinkingCheckBox))
                    .addComponent(peptideLengthsLabel)
                    .addComponent(sideReactionsLabel)
                    .addGroup(crossLinkingPanelLayout.createSequentialGroup()
                        .addComponent(serineCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(threonineCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tyrosineCheckBox))
                    .addGroup(crossLinkingPanelLayout.createSequentialGroup()
                        .addComponent(intralinkingLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(intraLinkingCheckBox))
                    .addGroup(crossLinkingPanelLayout.createSequentialGroup()
                        .addComponent(minimumPeptideLengthLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minimumPeptideLengthTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(maximumPeptideLengthLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maximumPeptideLengthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(355, Short.MAX_VALUE))
        );
        crossLinkingPanelLayout.setVerticalGroup(
            crossLinkingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crossLinkingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(crossLinkerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crossLinkerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(crossLinkerLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelingComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sideReactionsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(crossLinkingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serineCheckBox)
                    .addComponent(threonineCheckBox)
                    .addComponent(tyrosineCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(crossLinkingTypeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crosslinkingTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(crossLinkingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monolinkingLabel)
                    .addComponent(monoLinkingCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(peptideLengthsLabel)
                .addGap(2, 2, 2)
                .addGroup(crossLinkingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minimumPeptideLengthLabel)
                    .addComponent(minimumPeptideLengthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maximumPeptideLengthLabel)
                    .addComponent(maximumPeptideLengthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(crossLinkingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(intralinkingLabel)
                    .addComponent(intraLinkingCheckBox))
                .addContainerGap(153, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("Cross-linking", crossLinkingPanel);

        inSilicoDigestionPanel.setOpaque(false);

        enzymeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trypsin", "Trypsin_Mod", "Lys-C", "Lys-N", "Lys-C/P", "Arg-C", "Asp-N", "V8-E", "V8-DE", "Chymotrypsin", "Trypsin/P", "TrypChymo", "None", "NoCleavage", "dualArgC_Cathep", "dualArgC_Cathep/P", "Arg-C/P", " ", " " }));

        misCleavagesLabel.setText("Allowed number of miscleavages*:");

        misCleavagesTextField.setMinimumSize(new java.awt.Dimension(62, 27));
        misCleavagesTextField.setPreferredSize(new java.awt.Dimension(62, 27));

        minimumPeptideMassLabel.setText("Minimum peptide mass considered for cross-linked combinations*:");

        minimumPeptideMassTextField.setMinimumSize(new java.awt.Dimension(62, 27));
        minimumPeptideMassTextField.setPreferredSize(new java.awt.Dimension(62, 27));

        maximumPeptideMassLabel.setText("Maximum peptide mass considered for cross-linked combinations*:");

        maximumPeptideMassTextField.setMinimumSize(new java.awt.Dimension(62, 27));
        maximumPeptideMassTextField.setPreferredSize(new java.awt.Dimension(62, 27));

        enzymeLabel.setText("Select the enyme used for the in-silico digestion*:");

        javax.swing.GroupLayout inSilicoDigestionPanelLayout = new javax.swing.GroupLayout(inSilicoDigestionPanel);
        inSilicoDigestionPanel.setLayout(inSilicoDigestionPanelLayout);
        inSilicoDigestionPanelLayout.setHorizontalGroup(
            inSilicoDigestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inSilicoDigestionPanelLayout.createSequentialGroup()
                .addGroup(inSilicoDigestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enzymeLabel)
                    .addComponent(enzymeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(inSilicoDigestionPanelLayout.createSequentialGroup()
                        .addComponent(misCleavagesLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(misCleavagesTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(inSilicoDigestionPanelLayout.createSequentialGroup()
                        .addGroup(inSilicoDigestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(minimumPeptideMassLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(maximumPeptideMassLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(inSilicoDigestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(minimumPeptideMassTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maximumPeptideMassTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(470, Short.MAX_VALUE))
        );
        inSilicoDigestionPanelLayout.setVerticalGroup(
            inSilicoDigestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inSilicoDigestionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enzymeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enzymeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(inSilicoDigestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(misCleavagesLabel)
                    .addComponent(misCleavagesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(inSilicoDigestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minimumPeptideMassLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minimumPeptideMassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(inSilicoDigestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maximumPeptideMassLabel)
                    .addComponent(maximumPeptideMassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(319, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("In-silico digestion", inSilicoDigestionPanel);

        modificationsPanel.setOpaque(false);
        modificationsPanel.setLayout(new java.awt.GridBagLayout());

        fixedModificationsPanel.setOpaque(false);

        fixedModificationsLabel.setText("Select the fixed modifications*:");

        javax.swing.GroupLayout fixedModificationsPanelLayout = new javax.swing.GroupLayout(fixedModificationsPanel);
        fixedModificationsPanel.setLayout(fixedModificationsPanelLayout);
        fixedModificationsPanelLayout.setHorizontalGroup(
            fixedModificationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fixedModificationsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fixedModificationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fixedModificationsDualList, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                    .addGroup(fixedModificationsPanelLayout.createSequentialGroup()
                        .addComponent(fixedModificationsLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        fixedModificationsPanelLayout.setVerticalGroup(
            fixedModificationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixedModificationsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fixedModificationsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fixedModificationsDualList, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        modificationsPanel.add(fixedModificationsPanel, gridBagConstraints);

        variableModificationsPanel.setOpaque(false);

        variableModificationsLabel.setText("Select the variable modifications*:");

        javax.swing.GroupLayout variableModificationsPanelLayout = new javax.swing.GroupLayout(variableModificationsPanel);
        variableModificationsPanel.setLayout(variableModificationsPanelLayout);
        variableModificationsPanelLayout.setHorizontalGroup(
            variableModificationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(variableModificationsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(variableModificationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(variableModificationsList, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                    .addGroup(variableModificationsPanelLayout.createSequentialGroup()
                        .addComponent(variableModificationsLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        variableModificationsPanelLayout.setVerticalGroup(
            variableModificationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, variableModificationsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(variableModificationsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(variableModificationsList, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        modificationsPanel.add(variableModificationsPanel, gridBagConstraints);

        otherModSettingsPanel.setOpaque(false);

        maxModPeptideLabel.setText("Set the maximum number of modifications per peptide*:");

        javax.swing.GroupLayout otherModSettingsPanelLayout = new javax.swing.GroupLayout(otherModSettingsPanel);
        otherModSettingsPanel.setLayout(otherModSettingsPanelLayout);
        otherModSettingsPanelLayout.setHorizontalGroup(
            otherModSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otherModSettingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(maxModPeptideLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maxModPeptideTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(544, Short.MAX_VALUE))
        );
        otherModSettingsPanelLayout.setVerticalGroup(
            otherModSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otherModSettingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(otherModSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxModPeptideLabel)
                    .addComponent(maxModPeptideTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        modificationsPanel.add(otherModSettingsPanel, gridBagConstraints);

        mainTabbedPane.addTab("Modifications", modificationsPanel);

        scoringPanel.setOpaque(false);

        neutralLossesLabel.setText("Select the neutral losses to consider*:");

        neutralLossesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "no neutral losses are taken into account", "water losses for D/E/S/T and ammonia losses for K/N/Q/R (only singly charged)", "all water losses are considered (including doubly charged) ", " ", " " }));

        fragmentationLabel.setText("Select the fragmentation mode*:");

        fragmentationModeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HCD (b and y ions also a2)", "CID (b and y ions)", "ETD (c and z ions)", " ", " " }));

        peptideMassToleranceWindowsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Peptide mass tolerance windows"));
        peptideMassToleranceWindowsPanel.setOpaque(false);

        firstPeptideMassToleranceWindowValueLabel.setText("First peptide mass tolerance window size*:");

        firstPeptideMassToleranceWindowUnitLabel.setText("Unit*:");

        firstPeptideMassToleranceWindowUnitComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PPM", "Da" }));

        secondPeptideMassToleranceWindowValueLabel.setText("Second mass peptide tolerance window size*:");

        secondPeptideMassToleranceWindowUnitLabel.setText("Unit*:");

        secondPeptideMassToleranceWindowUnitComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PPM", "Da" }));

        thirdPeptideMassToleranceWindowValueLabel.setText("Third peptide mass tolerance window size*:");

        thirdPeptideMassToleranceWindowUnitLabel.setText("Unit*:");

        thirdPeptideMassToleranceWindowUnitComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PPM", "Da" }));

        fourthPeptideMassToleranceWindowValueLabel.setText("Fourth peptide mass tolerance window size*:");

        fourthPeptideMassToleranceWindowUnitLabel.setText("Unit*:");

        fourthPeptideMassToleranceWindowUnitComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PPM", "Da" }));

        jCheckBox1.setText("Use one peptide mass tolerance window value for all windows");

        peptideToleranceSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));

        peptideToleranceLabel.setText("Select the number of peptide tolerance windows*:");

        commonPeptideMassToleranceWindowLabel.setText("Value*:");

        commonPeptideMassToleranceWindowUnitLabel.setText("Unit*:");

        commonPeptideMassToleranceWindowUnitComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PPM", "Da" }));

        javax.swing.GroupLayout peptideMassToleranceWindowsPanelLayout = new javax.swing.GroupLayout(peptideMassToleranceWindowsPanel);
        peptideMassToleranceWindowsPanel.setLayout(peptideMassToleranceWindowsPanelLayout);
        peptideMassToleranceWindowsPanelLayout.setHorizontalGroup(
            peptideMassToleranceWindowsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(peptideMassToleranceWindowsPanelLayout.createSequentialGroup()
                .addGroup(peptideMassToleranceWindowsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(peptideMassToleranceWindowsPanelLayout.createSequentialGroup()
                        .addComponent(peptideToleranceLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(peptideToleranceSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(peptideMassToleranceWindowsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(peptideMassToleranceWindowsPanelLayout.createSequentialGroup()
                            .addGroup(peptideMassToleranceWindowsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(fourthPeptideMassToleranceWindowValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(firstPeptideMassToleranceWindowValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(secondPeptideMassToleranceWindowValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                                .addComponent(thirdPeptideMassToleranceWindowValueLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(peptideMassToleranceWindowsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(peptideMassToleranceWindowsPanelLayout.createSequentialGroup()
                                    .addComponent(fourthPeptideMassToleranceWindowTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(fourthPeptideMassToleranceWindowUnitLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(fourthPeptideMassToleranceWindowUnitComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(peptideMassToleranceWindowsPanelLayout.createSequentialGroup()
                                    .addComponent(firstPeptideMassToleranceWindowTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(firstPeptideMassToleranceWindowUnitLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(firstPeptideMassToleranceWindowUnitComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(peptideMassToleranceWindowsPanelLayout.createSequentialGroup()
                                    .addComponent(secondPeptideMassToleranceWindowTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(secondPeptideMassToleranceWindowUnitLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(secondPeptideMassToleranceWindowUnitComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(peptideMassToleranceWindowsPanelLayout.createSequentialGroup()
                                    .addComponent(thirdPeptideMassToleranceWindowTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(thirdPeptideMassToleranceWindowUnitLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(thirdPeptideMassToleranceWindowUnitComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(peptideMassToleranceWindowsPanelLayout.createSequentialGroup()
                            .addComponent(jCheckBox1)
                            .addGap(18, 18, 18)
                            .addComponent(commonPeptideMassToleranceWindowLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(commonPeptideMassToleranceWindowTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(commonPeptideMassToleranceWindowUnitLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(commonPeptideMassToleranceWindowUnitComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(237, Short.MAX_VALUE))
        );
        peptideMassToleranceWindowsPanelLayout.setVerticalGroup(
            peptideMassToleranceWindowsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(peptideMassToleranceWindowsPanelLayout.createSequentialGroup()
                .addGroup(peptideMassToleranceWindowsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(peptideToleranceLabel)
                    .addComponent(peptideToleranceSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(peptideMassToleranceWindowsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(commonPeptideMassToleranceWindowLabel)
                    .addComponent(commonPeptideMassToleranceWindowTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(peptideMassToleranceWindowsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(commonPeptideMassToleranceWindowUnitLabel)
                        .addComponent(commonPeptideMassToleranceWindowUnitComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(peptideMassToleranceWindowsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstPeptideMassToleranceWindowValueLabel)
                    .addComponent(firstPeptideMassToleranceWindowTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstPeptideMassToleranceWindowUnitLabel)
                    .addComponent(firstPeptideMassToleranceWindowUnitComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(peptideMassToleranceWindowsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(secondPeptideMassToleranceWindowValueLabel)
                    .addComponent(secondPeptideMassToleranceWindowTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secondPeptideMassToleranceWindowUnitLabel)
                    .addComponent(secondPeptideMassToleranceWindowUnitComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(peptideMassToleranceWindowsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thirdPeptideMassToleranceWindowTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thirdPeptideMassToleranceWindowUnitLabel)
                    .addComponent(thirdPeptideMassToleranceWindowUnitComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thirdPeptideMassToleranceWindowValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(peptideMassToleranceWindowsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fourthPeptideMassToleranceWindowValueLabel)
                    .addComponent(fourthPeptideMassToleranceWindowTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fourthPeptideMassToleranceWindowUnitLabel)
                    .addComponent(fourthPeptideMassToleranceWindowUnitComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        minNumberOfPeaksLabel.setText("Minimum number matched peaks for cross-linked peptides*:");

        peakMatchingLabel.setText("Peak matching*:");

        peakMatchingComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "find all matched theoretical peaks within a tolerance", "find only the closest theoretical peak within a tolerance " }));

        javax.swing.GroupLayout scoringPanelLayout = new javax.swing.GroupLayout(scoringPanel);
        scoringPanel.setLayout(scoringPanelLayout);
        scoringPanelLayout.setHorizontalGroup(
            scoringPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scoringPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(scoringPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(scoringPanelLayout.createSequentialGroup()
                        .addGroup(scoringPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(neutralLossesLabel)
                            .addComponent(neutralLossesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fragmentationLabel)
                            .addComponent(fragmentationModeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(peptideMassToleranceWindowsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(scoringPanelLayout.createSequentialGroup()
                        .addGroup(scoringPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(scoringPanelLayout.createSequentialGroup()
                                .addComponent(minNumberOfPeaksLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(minNumberOfPeaksTextField))
                            .addGroup(scoringPanelLayout.createSequentialGroup()
                                .addComponent(peakMatchingLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(peakMatchingComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        scoringPanelLayout.setVerticalGroup(
            scoringPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scoringPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(neutralLossesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(neutralLossesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fragmentationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fragmentationModeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(peptideMassToleranceWindowsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(scoringPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minNumberOfPeaksLabel)
                    .addComponent(minNumberOfPeaksTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(scoringPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(peakMatchingLabel)
                    .addComponent(peakMatchingComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("Scoring", scoringPanel);

        spectrumPreprocessingPanel.setOpaque(false);

        spectrumMassWindowValueLabel.setText("Spectrum scoring mass window value*:");

        minimumNumberOfPeaksLabel.setText("Minumum number of filtered peaks per window*:");

        maximumNumberOfPeaksLabel.setText("Maximum number of filtered peaks per window*:");

        lowerPrecursorMassBoundLabel.setText("Lower precursor mass bound for selecting the C13 peak over the C12 peak (in Da)*:");

        deisotopeLabel.setText("Allowed tolerance between the C12 peak and the C12 with one C13 fragment peak (in Da)*:");

        deconvulatePrecisionLabel.setText("Precision to select if a singly charged and its deconvoluted peak exist within this precision value (in Da)*:");

        javax.swing.GroupLayout spectrumPreprocessingPanelLayout = new javax.swing.GroupLayout(spectrumPreprocessingPanel);
        spectrumPreprocessingPanel.setLayout(spectrumPreprocessingPanelLayout);
        spectrumPreprocessingPanelLayout.setHorizontalGroup(
            spectrumPreprocessingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spectrumPreprocessingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(spectrumPreprocessingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(spectrumPreprocessingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(spectrumPreprocessingPanelLayout.createSequentialGroup()
                            .addComponent(maximumNumberOfPeaksLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(maximumNumberOfPeaksTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(spectrumPreprocessingPanelLayout.createSequentialGroup()
                            .addComponent(minimumNumberOfPeaksLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(minimumNumberOfPeaksTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(spectrumPreprocessingPanelLayout.createSequentialGroup()
                            .addComponent(spectrumMassWindowValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(spectrumMassWindowValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(spectrumPreprocessingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(spectrumPreprocessingPanelLayout.createSequentialGroup()
                            .addComponent(lowerPrecursorMassBoundLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lowerPrecursorMassBoundTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, spectrumPreprocessingPanelLayout.createSequentialGroup()
                            .addGroup(spectrumPreprocessingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(deisotopeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deconvulatePrecisionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(spectrumPreprocessingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(deconvulatePrecisionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(deisotopePrecisionTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(215, Short.MAX_VALUE))
        );
        spectrumPreprocessingPanelLayout.setVerticalGroup(
            spectrumPreprocessingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spectrumPreprocessingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(spectrumPreprocessingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spectrumMassWindowValueLabel)
                    .addComponent(spectrumMassWindowValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(spectrumPreprocessingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minimumNumberOfPeaksLabel)
                    .addComponent(minimumNumberOfPeaksTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(spectrumPreprocessingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maximumNumberOfPeaksLabel)
                    .addComponent(maximumNumberOfPeaksTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(spectrumPreprocessingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lowerPrecursorMassBoundLabel)
                    .addComponent(lowerPrecursorMassBoundTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(spectrumPreprocessingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deisotopeLabel)
                    .addComponent(deisotopePrecisionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(spectrumPreprocessingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deconvulatePrecisionLabel)
                    .addComponent(deconvulatePrecisionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(260, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("Spectrum preprocessing", spectrumPreprocessingPanel);

        multiThreadingAndValidationPanel.setOpaque(false);

        numberOfThreadsLabel.setText("Number of threads*:");

        writePercolatorInputFilesLabel.setText("Write separate Percolator input files*:");

        writePercolatorInputFilesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "yes", "no" }));

        fdrCalculationLabel.setText("<html>FDR calculation.<br>Improved means seperate XPSMs lists (T) into inter- and intra-protein XL sites to compute FDR for each subset.*:</html>");

        fdrCalcalationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "global", "improved" }));

        globalFdrValueLabel.setText("Global FDR value*:");

        interProteinFdrValueLabel.setText("Inter-protein improved FDR value*:");

        intraProteinFdrValueLabel.setText("Intra-protein improved FDR value*:");

        javax.swing.GroupLayout multiThreadingAndValidationPanelLayout = new javax.swing.GroupLayout(multiThreadingAndValidationPanel);
        multiThreadingAndValidationPanel.setLayout(multiThreadingAndValidationPanelLayout);
        multiThreadingAndValidationPanelLayout.setHorizontalGroup(
            multiThreadingAndValidationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(multiThreadingAndValidationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(multiThreadingAndValidationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fdrCalculationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fdrCalcalationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(multiThreadingAndValidationPanelLayout.createSequentialGroup()
                        .addComponent(intraProteinFdrValueLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(intraProteinFdrValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(multiThreadingAndValidationPanelLayout.createSequentialGroup()
                        .addGroup(multiThreadingAndValidationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(globalFdrValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(interProteinFdrValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(multiThreadingAndValidationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(globalFdrValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(interProteinFdrValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(multiThreadingAndValidationPanelLayout.createSequentialGroup()
                        .addGroup(multiThreadingAndValidationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(writePercolatorInputFilesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numberOfThreadsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(multiThreadingAndValidationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numberOfThreadsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(writePercolatorInputFilesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(245, Short.MAX_VALUE))
        );
        multiThreadingAndValidationPanelLayout.setVerticalGroup(
            multiThreadingAndValidationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(multiThreadingAndValidationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(multiThreadingAndValidationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberOfThreadsLabel)
                    .addComponent(numberOfThreadsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(multiThreadingAndValidationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(writePercolatorInputFilesLabel)
                    .addComponent(writePercolatorInputFilesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fdrCalculationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fdrCalcalationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(multiThreadingAndValidationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(globalFdrValueLabel)
                    .addComponent(globalFdrValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(multiThreadingAndValidationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(interProteinFdrValueLabel)
                    .addComponent(interProteinFdrValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(multiThreadingAndValidationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(intraProteinFdrValueLabel)
                    .addComponent(intraProteinFdrValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(228, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("Multithreading and validation", multiThreadingAndValidationPanel);

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainTabbedPane)
                .addContainerGap())
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainTabbedPane)
                .addContainerGap())
        );

        bottomPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        bottomPanel.setOpaque(false);

        closeButton.setText("close");
        closeButton.setMaximumSize(new java.awt.Dimension(85, 27));
        closeButton.setMinimumSize(new java.awt.Dimension(85, 27));
        closeButton.setPreferredSize(new java.awt.Dimension(85, 27));

        runButton.setText("run");
        runButton.setPreferredSize(new java.awt.Dimension(85, 27));

        javax.swing.GroupLayout bottomPanelLayout = new javax.swing.GroupLayout(bottomPanel);
        bottomPanel.setLayout(bottomPanelLayout);
        bottomPanelLayout.setHorizontalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottomPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(runButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        bottomPanelLayout.setVerticalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottomPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(runButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
                    .addComponent(bottomPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bottomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel commonPeptideMassToleranceWindowLabel;
    private javax.swing.JTextField commonPeptideMassToleranceWindowTextField;
    private javax.swing.JComboBox<String> commonPeptideMassToleranceWindowUnitComboBox;
    private javax.swing.JLabel commonPeptideMassToleranceWindowUnitLabel;
    private javax.swing.JButton contaminantsFastaDbBrowseButton;
    private javax.swing.JLabel contaminantsFastaDbFilePathLabel;
    private javax.swing.JTextField contaminantsFastaDbPathTextField;
    private javax.swing.JComboBox<String> crossLinkerComboBox;
    private javax.swing.JLabel crossLinkerLabel;
    private javax.swing.JLabel crossLinkerLabel1;
    private javax.swing.JPanel crossLinkingPanel;
    private javax.swing.JLabel crossLinkingTypeLabel;
    private javax.swing.JComboBox<String> crosslinkingTypeComboBox;
    private javax.swing.JLabel deconvulatePrecisionLabel;
    private javax.swing.JTextField deconvulatePrecisionTextField;
    private javax.swing.JLabel deisotopeLabel;
    private javax.swing.JTextField deisotopePrecisionTextField;
    private javax.swing.JComboBox<String> enzymeComboBox;
    private javax.swing.JLabel enzymeLabel;
    private javax.swing.JButton fastaDbBrowseButton;
    private javax.swing.JLabel fastaDbPathLabel;
    private javax.swing.JTextField fastaDbPathTextField;
    private javax.swing.JComboBox<String> fdrCalcalationComboBox;
    private javax.swing.JLabel fdrCalculationLabel;
    private javax.swing.JTextField firstPeptideMassToleranceWindowTextField;
    private javax.swing.JComboBox<String> firstPeptideMassToleranceWindowUnitComboBox;
    private javax.swing.JLabel firstPeptideMassToleranceWindowUnitLabel;
    private javax.swing.JLabel firstPeptideMassToleranceWindowValueLabel;
    private gui.DualList fixedModificationsDualList;
    private javax.swing.JLabel fixedModificationsLabel;
    private javax.swing.JPanel fixedModificationsPanel;
    private javax.swing.JTextField fourthPeptideMassToleranceWindowTextField;
    private javax.swing.JComboBox<String> fourthPeptideMassToleranceWindowUnitComboBox;
    private javax.swing.JLabel fourthPeptideMassToleranceWindowUnitLabel;
    private javax.swing.JLabel fourthPeptideMassToleranceWindowValueLabel;
    private javax.swing.JLabel fragmentationLabel;
    private javax.swing.JComboBox<String> fragmentationModeComboBox;
    private javax.swing.JLabel globalFdrValueLabel;
    private javax.swing.JTextField globalFdrValueTextField;
    private javax.swing.JPanel inSilicoDigestionPanel;
    private javax.swing.JPanel inputOutputPanel;
    private javax.swing.JLabel interProteinFdrValueLabel;
    private javax.swing.JTextField interProteinFdrValueTextField;
    private javax.swing.JCheckBox intraLinkingCheckBox;
    private javax.swing.JLabel intraProteinFdrValueLabel;
    private javax.swing.JTextField intraProteinFdrValueTextField;
    private javax.swing.JLabel intralinkingLabel;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JComboBox<String> labelingComboBox;
    private javax.swing.JLabel lowerPrecursorMassBoundLabel;
    private javax.swing.JTextField lowerPrecursorMassBoundTextField;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JLabel maxModPeptideLabel;
    private javax.swing.JTextField maxModPeptideTextField;
    private javax.swing.JLabel maximumNumberOfPeaksLabel;
    private javax.swing.JTextField maximumNumberOfPeaksTextField;
    private javax.swing.JLabel maximumPeptideLengthLabel;
    private javax.swing.JTextField maximumPeptideLengthTextField;
    private javax.swing.JLabel maximumPeptideMassLabel;
    private javax.swing.JTextField maximumPeptideMassTextField;
    private javax.swing.JLabel minNumberOfPeaksLabel;
    private javax.swing.JTextField minNumberOfPeaksTextField;
    private javax.swing.JLabel minimumNumberOfPeaksLabel;
    private javax.swing.JTextField minimumNumberOfPeaksTextField;
    private javax.swing.JLabel minimumPeptideLengthLabel;
    private javax.swing.JTextField minimumPeptideLengthTextField;
    private javax.swing.JLabel minimumPeptideMassLabel;
    private javax.swing.JTextField minimumPeptideMassTextField;
    private javax.swing.JLabel misCleavagesLabel;
    private javax.swing.JTextField misCleavagesTextField;
    private javax.swing.JPanel modificationsPanel;
    private javax.swing.JCheckBox monoLinkingCheckBox;
    private javax.swing.JLabel monolinkingLabel;
    private javax.swing.JPanel multiThreadingAndValidationPanel;
    private javax.swing.JComboBox<String> neutralLossesComboBox;
    private javax.swing.JLabel neutralLossesLabel;
    private javax.swing.JLabel numberOfThreadsLabel;
    private javax.swing.JTextField numberOfThreadsTextField;
    private javax.swing.JPanel otherModSettingsPanel;
    private javax.swing.JButton outputDirectoryBrowseButton;
    private javax.swing.JLabel outputDirectoryPathLabel;
    private javax.swing.JTextField outputDirectoryPathTextField;
    private javax.swing.JComboBox<String> peakMatchingComboBox;
    private javax.swing.JLabel peakMatchingLabel;
    private javax.swing.JLabel peptideLengthsLabel;
    private javax.swing.JPanel peptideMassToleranceWindowsPanel;
    private javax.swing.JLabel peptideToleranceLabel;
    private javax.swing.JSpinner peptideToleranceSpinner;
    private javax.swing.JButton runButton;
    private javax.swing.JPanel scoringPanel;
    private javax.swing.JButton searchDbBrowseButton;
    private javax.swing.JLabel searchDbPathLabel;
    private javax.swing.JTextField searchDbPathTextField1;
    private javax.swing.JTextField secondPeptideMassToleranceWindowTextField;
    private javax.swing.JComboBox<String> secondPeptideMassToleranceWindowUnitComboBox;
    private javax.swing.JLabel secondPeptideMassToleranceWindowUnitLabel;
    private javax.swing.JLabel secondPeptideMassToleranceWindowValueLabel;
    private javax.swing.JCheckBox serineCheckBox;
    private javax.swing.JLabel sideReactionsLabel;
    private javax.swing.JLabel spectrumMassWindowValueLabel;
    private javax.swing.JTextField spectrumMassWindowValueTextField;
    private javax.swing.JPanel spectrumPreprocessingPanel;
    private javax.swing.JTextField thirdPeptideMassToleranceWindowTextField;
    private javax.swing.JComboBox<String> thirdPeptideMassToleranceWindowUnitComboBox;
    private javax.swing.JLabel thirdPeptideMassToleranceWindowUnitLabel;
    private javax.swing.JLabel thirdPeptideMassToleranceWindowValueLabel;
    private javax.swing.JCheckBox threonineCheckBox;
    private javax.swing.JPanel topPanel;
    private javax.swing.JCheckBox tyrosineCheckBox;
    private javax.swing.JButton validatedTargetHitsBrowseButton;
    private javax.swing.JLabel validatedTargetHitsPathLabel;
    private javax.swing.JTextField validatedTargetHitsPathTextField;
    private javax.swing.JLabel variableModificationsLabel;
    private gui.DualList variableModificationsList;
    private javax.swing.JPanel variableModificationsPanel;
    private javax.swing.JComboBox<String> writePercolatorInputFilesComboBox;
    private javax.swing.JLabel writePercolatorInputFilesLabel;
    private javax.swing.JButton xpsmsBrowseButton;
    private javax.swing.JLabel xpsmsPathLabel;
    private javax.swing.JTextField xpsmsPathTextField;
    // End of variables declaration//GEN-END:variables
}
